# Generated by Django 3.0.3 on 2020-06-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctors_pics')),
                ('name', models.CharField(max_length=40)),
                ('expert', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
            ],
        ),
    ]
