# Generated by Django 3.0.3 on 2020-06-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors_List',
            new_name='DoctorsList',
        ),
    ]
