# Generated by Django 3.0.3 on 2020-06-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('phone', models.IntegerField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('appointment_time', models.TimeField()),
                ('appointment_date', models.DateField()),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
