# Generated by Django 3.0.3 on 2020-06-21 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_auto_20200621_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='MessageUser',
        ),
    ]
