# Generated by Django 3.0.3 on 2020-06-21 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_auto_20200621_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageuser',
            old_name='messages',
            new_name='information',
        ),
    ]
