# Generated by Django 3.0.3 on 2020-06-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0006_auto_20200621_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageuser',
            name='information',
            field=models.TextField(max_length=260),
        ),
    ]
